remote_theme: brockfanning/open-sdg@open-sdg-by-country-features
environment: production
languages:
  - en
data_edit_url: http://prose.io/#my-org/my-repo/edit/develop/data/indicator_[id].csv
metadata_edit_url: http://prose.io/#my-org/my-repo/edit/develop/meta/[id].md
create_indicators:
  layout: indicator
create_goals:
  layout: goal-by-target
create_pages: true
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body
menu:
  - path: about
    translation_key: menu.about
  - path: reporting-status
    translation_key: menu.reporting_status
footer_menu:
  - path: about/cookies-and-privacy
    translation_key: menu.cookies
non_global_metadata: indicator.national_metadata
goal_image_base: https://open-sdg.github.io/sdg-translations/assets/img/goals
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE
  - Makefile
accessible_tabs: true
accessible_charts: true
series_toggle: true
data_fields:
  units: UNIT_MEASURE
  series: SERIES
metadata_tabs:
  - scope: global
    title: indicator.global_metadata
    description: indicator.global_metadata_blurb
  - scope: sources
    title: indicator.sources
    description: ''
hide_empty_metadata: true
